# Definition of connections in map, city1, city2 and cost of connection
# and definition of tickets with points
connections:
  - cities: [Paris, Brest]
    cost: [black, black, black]

  - cities: [Brest, Palermo]
    cost: [pink, pink, pink, pink]

  - cities: [Paris, Palermo]
    cost: [green, green, green, green]

  - cities: [Paris, Palermo]
    cost: [blue, blue, blue, blue]

  - cities: [Paris, Bordeaux]
    cost: [pink]

tickets:
  - cities: [Paris, Brest]
    points: 5
  
  - cities: [Brest, Palermo]
    points: 8

  - cities: [Paris, Palermo]
    points: 7 

cities:
  - name: Bordeaux
    x: 181
    y: 365
  - name: Brest
    x: 111
    y: 297
  - name: Palermo
    x: 392
    y: 521
  - name: Paris
    x: 212
    y: 308
  - name: Warsaw
    x: 549
    y: 231
  - name: London
    x: 184
    y: 206
  - name: Barcelona
    x: 185
    y: 500
  - name: Madrid
    x: 100
    y: 490
  - name: Vilnius 
    x: 627
    y: 219
  - name: Danzig
    x: 490
    y: 140
  - name: Berlin
    x: 393
    y: 220
  - name: Essen
    x: 323
    y: 200
  - name: Amsterdam
    x: 257
    y: 190
  - name: Munich
    x: 350
    y: 282
  - name: Frankfurt
    x: 318
    y: 240
  - name: Pamplona
    x: 158
    y: 428
  - name: Brussels
    x: 246
    y: 227
  - name: Marseille
    x: 292
    y: 412