# Definition of connections in map, city1, city2 and cost of connection
# and definition of tickets with points
connections:
  - cities: [Paris, Brest]
    cost: [black, black, black]

  - cities: [Brest, Paloma]
    cost: [pink, pink, pink, pink]

  - cities: [Paris, Paloma]
    cost: [green, green, green, green]

  - cities: [Paris, Paloma]
    cost: [blue, blue, blue, blue]

  - cities: [Paris, Dieppe]
    cost: [pink]

tickets:
  - cities: [Paris, Brest]
    points: 5
  
  - cities: [Brest, Paloma]
    points: 8

  - cities: [Paris, Paloma]
    points: 7 

cities:
  - name: Paris
    x: 100
    y: 200

  - name: Brest
    x: 300
    y: 400

  - name: Paloma
    x: 500
    y: 500

  - name: Dieppe
    x: 400
    y: 500