# Definition of connections in map, city1, city2 and cost of connection
# and definition of tickets with points
connections:
  - cities: [Paris, Brest]
    cost: [black, black, black]

  - cities: [Brest, Paloma]
    cost: [pink, pink, pink, pink]

  - cities: [Paris, Paloma]
    cost: [green, green, green, green]

  - cities: [Paris, Paloma]
    cost: [blue, blue, blue, blue]

  - cities: [Paris, Bordeaux]
    cost: [pink]

tickets:
  - cities: [Paris, Brest]
    points: 5
  
  - cities: [Brest, Paloma]
    points: 8

  - cities: [Paris, Paloma]
    points: 7 

cities:
  - name: Aarhus
    x: 684
    y: 393
  - name: Alicante
    x: 273
    y: 850
  - name: Almeria
    x: 218
    y: 882
  - name: Amsterdam
    x: 493
    y: 526
  - name: Andorra
    x: 350
    y: 719
  - name: Antwerp
    x: 482
    y: 508
  - name: Athens
    x: 815
    y: 884
  - name: BanjaLuka
    x: 702
    y: 734
  - name: Barcelona
    x: 270
    y: 776
  - name: Bari
    x: 670
    y: 750
  - name: Basel
    x: 514
    y: 598
  - name: Belgrade
    x: 778
    y: 711
  - name: Bergen
    x: 628
    y: 278
  - name: Berlin
    x: 640
    y: 526
  - name: Bern
    x: 478
    y: 598
  - name: Bilbao
    x: 258
    y: 743
  - name: Bitola
    x: 758
    y: 778
  - name: Bologna
    x: 596
    y: 688
  - name: Bordeaux
    x: 331
    y: 667
  - name: Brescia
    x: 566
    y: 656
  - name: Brest
    x: 300
    y: 531
  - name: Bratislava
    x: 687
    y: 628
  - name: Brno
    x: 679
    y: 585
  - name: Bruges
    x: 462
    y: 504
  - name: Brussels
    x: 473
    y: 524
  - name: Bucharest
    x: 856
    y: 654
  - name: Budapest
    x: 749
    y: 662
  - name: Burgas
    x: 884
    y: 730
  - name: Cagliari
    x: 554
    y: 833
  - name: Catania
    x: 672
    y: 861
  - name: Chania
    x: 744
    y: 919
  - name: Cluj
    x: 814
    y: 607
  - name: Cologne
    x: 514
    y: 574
  - name: Constanta
    x: 905
    y: 670
  - name: Copenhagen
    x: 639
    y: 415
  - name: Cork
    x: 234
    y: 472
  - name: Daugavpils
    x: 867
    y: 429
  - name: Debrecen
    x: 783
    y: 625
  - name: Dortmund
    x: 533
    y: 560
  - name: Dresden
    x: 668
    y: 557
  - name: Drobeta
    x: 832
    y: 639
  - name: Dublin
    x: 257
    y: 466
  - name: Elbasan
    x: 781
    y: 812
  - name: Faro
    x: 107
    y: 889
  - name: Florence
    x: 614
    y: 713
  - name: Frankfurt
    x: 557
    y: 600
  - name: Funchal
    x: 54
    y: 892
  - name: Galway
    x: 216
    y: 451
  - name: Gdansk
    x: 704
    y: 492
  - name: Geneva
    x: 459
    y: 600
  - name: Genoa
    x: 566
    y: 677
  - name: Gent
    x: 466
    y: 518
  - name: Giurgiu
    x: 860
    y: 686
  - name: Graz
    x: 667
    y: 656
  - name: Hamburg
    x: 623
    y: 448
  - name: Heraklion
    x: 782
    y: 940
  - name: Helsinki
    x: 790
    y: 304
  - name: Innsbruck
    x: 582
    y: 621
  - name: Istanbul
    x: 967
    y: 822
  - name: Kaunas
    x: 815
    y: 445
  - name: Kavala
    x: 847
    y: 833
  - name: Kecskemet
    x: 760
    y: 649
  - name: Klaipeda
    x: 800
    y: 420
  - name: Kotor
    x: 717
    y: 762
  - name: Krakow
    x: 785
    y: 602
  - name: LaCoruna
    x: 187
    y: 719
  - name: Leipzig
    x: 640
    y: 529
  - name: Liege
    x: 492
    y: 538
  - name: Lisbon
    x: 135
    y: 823
  - name: Ljubljana
    x: 651
    y: 664
  - name: Linz
    x: 636
    y: 616
  - name: Livorno
    x: 585
    y: 693
  - name: Lodz
    x: 746
    y: 501
  - name: Lugano
    x: 537
    y: 612
  - name: Luxembourg
    x: 478
    y: 540
  - name: Lviv
    x: 832
    y: 558
  - name: Lyon
    x: 429
    y: 616
  - name: Madrid
    x: 222
    y: 791
  - name: Malaga
    x: 180
    y: 848
  - name: Malmo
    x: 666
    y: 392
  - name: Maribor
    x: 655
    y: 656
  - name: Marseille
    x: 469
    y: 671
  - name: Metz
    x: 487
    y: 562
  - name: Milan
    x: 557
    y: 633
  - name: Minsk
    x: 901
    y: 479
  - name: Modena
    x: 585
    y: 728
  - name: Monaco
    x: 567
    y: 671
  - name: Moscow
    x: 1024
    y: 374
  - name: Munich
    x: 610
    y: 609
  - name: Naples
    x: 655
    y: 791
  - name: Nantes
    x: 336
    y: 604
  - name: Nice
    x: 513
    y: 682
  - name: Nicosia
    x: 902
    y: 966
  - name: NoviSad
    x: 754
    y: 683
  - name: Nuremberg
    x: 606
    y: 579
  - name: Oradea
    x: 797
    y: 656
  - name: Oslo
    x: 650
    y: 318
  - name: Paloma
    x: 265
    y: 732
  - name: Paris
    x: 391
    y: 567
  - name: Patras
    x: 768
    y: 833
  - name: Perugia
    x: 610
    y: 713
  - name: Petersburg
    x: 935
    y: 315
  - name: Pisa
    x: 578
    y: 705
  - name: Plovdiv
    x: 822
    y: 750
  - name: Podgorica
    x: 727
    y: 743
  - name: Poděbrady
    x: 655
    y: 567
  - name: Porto
    x: 163
    y: 786
  - name: Poznan
    x: 696
    y: 519
  - name: Prague
    x: 649
    y: 565
  - name: Reims
    x: 448
    y: 543
  - name: Reykjavik
    x: 201
    y: 101
  - name: Riga
    x: 843
    y: 400
  - name: Rijeka
    x: 656
    y: 671
  - name: Rome
    x: 609
    y: 706
  - name: Rotterdam
    x: 499
    y: 508
  - name: Ruse
    x: 861
    y: 696
  - name: Sassari
    x: 523
    y: 808
  - name: Sarajevo
    x: 729
    y: 769
  - name: Seville
    x: 190
    y: 833
  - name: Shumen
    x: 869
    y: 712
  - name: Skopje
    x: 765
    y: 756
  - name: Sliven
    x: 869
    y: 728
  - name: Sofia
    x: 815
    y: 724
  - name: Split
    x: 680
    y: 741
  - name: Stuttgart
    x: 556
    y: 585
  - name: Szeged
    x: 779
    y: 666
  - name: Tallinn
    x: 832
    y: 342
  - name: Tartu
    x: 832
    y: 319
  - name: Thessaloniki
    x: 827
    y: 822
  - name: Timisoara
    x: 791
    y: 641
  - name: Torino
    x: 527
    y: 632
  - name: Toulouse
    x: 350
    y: 684
  - name: Trento
    x: 575
    y: 634
  - name: Trieste
    x: 632
    y: 652
  - name: Tirana
    x: 760
    y: 799
  - name: Turin
    x: 528
    y: 623
  - name: Uzhhorod
    x: 765
    y: 596
  - name: Valencia
    x: 254
    y: 854
  - name: Varna
    x: 916
    y: 724
  - name: Venice
    x: 593
    y: 671
  - name: Vienna
    x: 659
    y: 616
  - name: Vigo
    x: 163
    y: 750
  - name: Vilnius
    x: 832
    y: 465
  - name: Warsaw
    x: 784
    y: 534
  - name: Zagreb
    x: 692
    y: 671
  - name: Zaragoza
    x: 282
    y: 732
  - name: Zilina
    x: 698
    y: 599