# Definition of connections in map, city1, city2 and cost of connection
# and definition of tickets with points
connections:
  - cities: [Paris, Brest]
    cost: [black, black, black, locomotive]

  # - cities: [Paris, Brest]
  #   cost: [blue, blue, blue]

  - cities: [Brest, Paloma]
    cost: [pink, pink, pink, pink]

  - cities: [Paris, Paloma]
    cost: [green, green, green, green]

  - cities: [Paloma, Bordeaux]
    cost: [pink]


tickets:
  - cities: [Paris, Brest]
    points: 5
  

  - cities: [Brest, Paloma]
    points: 8

  - cities: [Paris, Paloma]
    points: 7 

  - cities: [Paris, Bordeaux]
    points: 4

  - cities: [Brest, Bordeaux]
    points: 6

  - cities: [Paloma, Bordeaux]
    points: 9

  - cities: [Brest, Bordeaux]
    points: 10

cities:
  - name: Brest
    x: 300
    y: 531
  - name: Bordeaux
    x: 200
    y: 600
  - name: Paloma
    x: 265
    y: 732
  - name: Paris
    x: 391
    y: 567
  - name: Prague
    x: 649
    y: 565
  