# Ticket to Ride Europe Map - city connections
connections:
  - cities: [Edinburgh, London]
    cost: [black, black, black, black]
  
  - cities: [London, Amsterdam]
    cost: [blue, blue]
  
  - cities: [London, Dieppe]
    cost: [gray, gray]
  
  - cities: [London, Paris]
    cost: [yellow, yellow]
  
  - cities: [Amsterdam, Brussels]
    cost: [black]
  
  - cities: [Amsterdam, Frankfurt]
    cost: [white, white]
  
  - cities: [Amsterdam, Essen]
    cost: [yellow, yellow, yellow]
  
  - cities: [Dieppe, Brussels]
    cost: [green, green]
  
  - cities: [Dieppe, Paris]
    cost: [purple]
  
  - cities: [Brussels, Paris]
    cost: [red, red]
  
  - cities: [Brussels, Frankfurt]
    cost: [blue, blue]
  
  - cities: [Paris, Frankfurt]
    cost: [white, white, white]
  
  - cities: [Paris, Zurich]
    cost: [gray, gray, gray]
  
  - cities: [Paris, Marseille]
    cost: [gray, gray, gray, gray]
  
  - cities: [Paris, Pamplona]
    cost: [blue, blue, blue, blue]
  
  - cities: [Paris, Brest]
    cost: [black, black, black]
  
  - cities: [Brest, Pamplona]
    cost: [purple, purple, purple, purple]
  
  - cities: [Pamplona, Madrid]
    cost: [black, black, black]
  
  - cities: [Pamplona, Barcelona]
    cost: [gray, gray]
  
  - cities: [Pamplona, Marseille]
    cost: [red, red, red, red]
  
  - cities: [Madrid, Lisboa]
    cost: [purple, purple, purple]
  
  - cities: [Madrid, Cadiz]
    cost: [orange, orange, orange]
  
  - cities: [Madrid, Barcelona]
    cost: [yellow, yellow]
  
  - cities: [Lisboa, Cadiz]
    cost: [blue, blue]
  
  - cities: [Barcelona, Marseille]
    cost: [orange, orange, orange, orange]
  
  - cities: [Marseille, Zurich]
    cost: [purple, purple]
  
  - cities: [Marseille, Roma]
    cost: [gray, gray, gray, gray]
  
  - cities: [Zurich, Munchen]
    cost: [yellow, yellow]
  
  - cities: [Zurich, Venezia]
    cost: [green, green]
  
  - cities: [Frankfurt, Munchen]
    cost: [purple, purple]
  
  - cities: [Frankfurt, Berlin]
    cost: [black, black, black]
  
  - cities: [Frankfurt, Essen]
    cost: [green, green]
  
  - cities: [Essen, Berlin]
    cost: [blue, blue]
  
  - cities: [Essen, Kobenhavn]
    cost: [gray, gray, gray]
  
  - cities: [Kobenhavn, Stockholm]
    cost: [yellow, yellow, yellow]
  
  - cities: [Stockholm, Petrograd]
    cost: [white, white, white, white, white, white, white, white]
  
  - cities: [Petrograd, Riga]
    cost: [gray, gray, gray, gray]
  
  - cities: [Petrograd, Moskva]
    cost: [white, white, white, white]
  
  - cities: [Riga, Wilno]
    cost: [green, green, green, green]
  
  - cities: [Riga, Danzig]
    cost: [black, black, black]
  
  - cities: [Danzig, Warszawa]
    cost: [gray, gray]
  
  - cities: [Danzig, Berlin]
    cost: [gray, gray, gray, gray]
  
  - cities: [Berlin, Warszawa]
    cost: [purple, purple, purple, purple]
  
  - cities: [Berlin, Wien]
    cost: [green, green, green]
  
  - cities: [Warszawa, Wien]
    cost: [blue, blue, blue, blue]
  
  - cities: [Warszawa, Wilno]
    cost: [red, red, red]
  
  - cities: [Warszawa, Kyiv]
    cost: [gray, gray, gray, gray]
  
  - cities: [Wilno, Kyiv]
    cost: [gray, gray]
  
  - cities: [Wilno, Smolensk]
    cost: [yellow, yellow, yellow]
  
  - cities: [Smolensk, Moskva]
    cost: [orange, orange]
  
  - cities: [Moskva, Kyiv]
    cost: [blue, blue, blue, blue]
  
  - cities: [Kyiv, Kharkiv]
    cost: [gray, gray, gray, gray]
  
  - cities: [Kyiv, Budapest]
    cost: [gray, gray, gray, gray, gray, gray]
  
  - cities: [Budapest, Wien]
    cost: [red]
  
  - cities: [Budapest, Bucuresti]
    cost: [gray, gray, gray, gray]
  
  - cities: [Budapest, Zagrab]
    cost: [orange, orange]
  
  - cities: [Wien, Zagrab]
    cost: [gray, gray]
  
  - cities: [Wien, Munchen]
    cost: [orange, orange, orange]
  
  - cities: [Munchen, Venezia]
    cost: [blue, blue]
  
  - cities: [Venezia, Zagrab]
    cost: [gray, gray]
  
  - cities: [Venezia, Roma]
    cost: [black, black]
  
  - cities: [Roma, Palermo]
    cost: [gray, gray, gray, gray]
  
  - cities: [Roma, Brindisi]
    cost: [white, white]
  
  - cities: [Palermo, Brindisi]
    cost: [gray, gray, gray]
  
  - cities: [Palermo, Smyrna]
    cost: [gray, gray, gray, gray, gray, gray]
  
  - cities: [Brindisi, Athina]
    cost: [gray, gray, gray, gray]
  
  - cities: [Zagrab, Sarajevo]
    cost: [red, red, red]
  
  - cities: [Sarajevo, Budapest]
    cost: [gray, gray, gray]
  
  - cities: [Sarajevo, Sofia]
    cost: [gray, gray]
  
  - cities: [Sarajevo, Athina]
    cost: [green, green, green, green]
  
  - cities: [Bucuresti, Kyiv]
    cost: [gray, gray, gray, gray]
  
  - cities: [Bucuresti, Sevastopol]
    cost: [white, white, white, white]
  
  - cities: [Bucuresti, Sofia]
    cost: [gray, gray]
  
  - cities: [Sofia, Athina]
    cost: [purple, purple, purple]
  
  - cities: [Sofia, Constantinople]
    cost: [blue, blue, blue]
  
  - cities: [Athina, Smyrna]
    cost: [red, red]
  
  - cities: [Sevastopol, Sochi]
    cost: [gray, gray]
  
  - cities: [Sevastopol, Rostov]
    cost: [gray, gray, gray, gray]
  
  - cities: [Sevastopol, Constantinople]
    cost: [gray, gray, gray, gray]
  
  - cities: [Constantinople, Angora]
    cost: [gray, gray]
  
  - cities: [Constantinople, Smyrna]
    cost: [red, red]
  
  - cities: [Smyrna, Angora]
    cost: [orange, orange, orange]
  
  - cities: [Angora, Erzurum]
    cost: [black, black, black]
  
  - cities: [Erzurum, Sochi]
    cost: [red, red, red]
  
  - cities: [Sochi, Rostov]
    cost: [gray, gray]
  
  - cities: [Rostov, Kharkiv]
    cost: [green, green]
  
  - cities: [Kharkiv, Kyiv]
    cost: [gray, gray, gray, gray]